name: CI/CD Pipeline

on:
   push:
     branches:["master"]
   pull_request:
     branches:["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: timescale/timescaledb:2.17.2-pg16
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          -5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
     -users: actions/checkout@v3

     -name: Set up Docker
      uses: docker/setup-buildx-action@v2

     - name: Build all docker-compose services
       run: docker-compose -f docker-compose.yml build

     - name: Run tests (пример)
       run: |
          docker-compose run --rm app ./mvn clean package          
